### ISSUE TITLE
Update Style of "New Joke" Button

### ISSUE THREAD

**Issue by SachinMittal1766** [ExpressHermes/JokesApp#7]
The current button can be styled in a better way. I am attaching my style and want to contribute to it. @ExpressHermes Pls assign it to me.  
![New Joke Button](https://user-images.githubusercontent.com/82721772/144699689-93905d83-b585-4069-932b-3d69776dd6af.png)

**Comment by ExpressHermes** [comment]
Duplicate of #1. When the UI is redesigned, this will already be included in that.

**Comment by SachinMittal1766** [comment]
@ExpressHermes I would like to work on UI of project.

**Comment by ExpressHermes** [comment]
You are welcome to share your ideas/PRs.
